//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Color.java
//  @ Date : 13/03/2006
//  @ Author : 
//
//



package es.forman.cursojava.formas;


public class Color {
	private int r;
	private int g;
	private int b;
        
        public void setR(int valor) {
                this.r = valor;
        }
        
        public int getR() {
                return r;
        }
        
        public void setB(int valor) {
                this.b = valor;
        }
        
        public int getB() {
                return b;
        }

        public void setG(int valor) {
                this.g = valor;
        }
        
        public int getG() {
                return g;
        }
}