//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Capa.java
//  @ Date : 13/03/2006
//  @ Author : 
//
//



package es.forman.cursojava.formas;


public class Capa {
	public Object nivel;
	public Object anchura;
	public Object altura;
	public void cambiarNivel(int nivel) {
	
	}
	
	public void cambiaPosicion(Coordenadas coor) {
	
	}
	
	public void añadirFigura(FormaGeometrica figura) {
	
	}
	
	public void borra() {
	
	}
	
	public void isRoot() {
	
	}
}
