//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuadrado.java
//  @ Date : 13/03/2006
//  @ Author : 
//
//



package es.forman.cursojava.formas;


public class Cuadrado extends Rectangulo {
	private float lado;
    
	public Cuadrado(float lado) {
	  this.lado=lado;
	}
	
	/*
	 * si solo tuvieramos en clase padre el
	 * constructor sobreescrito (float,float)
	 * y no especificamos constructor defecto
	public Cuadrado(float lado) {
		  super(lado,lado);
		}
	*/
	public float getLado() {
	  return lado;
	}
	
}