//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FormaGeometrica.java
//  @ Date : 13/03/2006
//  @ Author : 
//
//



package es.forman.cursojava.formas;


public class FormaGeometrica {
	public Color color;
	public Coordenadas posicion;

	public void borra() {
	
	}
	
	public void dibuja(Color color) {
	
	}
	
	public void mueve(Coordenadas coordenada) {
	
	}
	
	public void isCapa() {
	
	}
	
	public void añadirFoto(Foto f) {
	
	}
}