//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PoligonoIrregular.java
//  @ Date : 13/03/2006
//  @ Author : 
//
//



package es.forman.cursojava.formas;

import java.util.ArrayList;


public class PoligonoIrregular extends FormaGeometrica {
	@SuppressWarnings("unused")
	private int lados;
	public ArrayList vertices;

	
	public PoligonoIrregular(int lados) {
	  this.lados=lados;
	}
	
	public void Operation1() {
	
	}
}
