//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rectangulo.java
//  @ Date : 13/03/2006
//  @ Author : 
//
//



package es.forman.cursojava.formas;


public class Rectangulo extends FormaGeometrica {
	@SuppressWarnings("unused")
	private float lado1;
	@SuppressWarnings("unused")
	private float lado2;


	public Rectangulo() {}
	public Rectangulo(float lado1, float lado2) {
	    this.lado1=lado1;
	    this.lado2=lado2;
	}
	


	public void diagonal() {
	
	}
}