//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuenta.java
//  @ Date : 16/03/2006
//  @ Author : 
//
//
package es.forman.cursojava.banco.cuentas;

public abstract class Cuenta implements IFCuenta {

	private float saldo;
	private String numero;
	
	public Cuenta(float cantidadInicial, String numeroCuenta) {
			this.saldo = cantidadInicial;
			this.numero = numeroCuenta;
	}
	
	/* (non-Javadoc)
	 * @see es.forman.cursojava.cajero.IFCuenta#getSaldo()
	 */
	public float getSaldo() {
		return this.saldo;
	}
	
	/* (non-Javadoc)
	 * @see es.forman.cursojava.cajero.IFCuenta#setSaldo(float)
	 */
	public void setSaldo(float cantidad) {
		this.saldo = cantidad;
	}
	
	/* (non-Javadoc)
	 * @see es.forman.cursojava.cajero.IFCuenta#reintegra(float, boolean)
	 */
	public abstract int reintegra(float cantidad,  boolean ejecuta);
	
	
	/* (non-Javadoc)
	 * @see es.forman.cursojava.cajero.IFCuenta#getDisponible()
	 */
	public float getDisponible() {
		return this.getSaldo();
	}

    /* (non-Javadoc)
	 * @see es.forman.cursojava.cajero.IFCuenta#isDisponible(float)
	 */
    public final boolean isDisponible(float cantidad)  {
    	return (this.getDisponible() >= cantidad);
    }
    
    /* (non-Javadoc)
	 * @see es.forman.cursojava.cajero.IFCuenta#getTipoInteres()
	 */
    public abstract float getTipoInteres();
    
    /* (non-Javadoc)
	 * @see es.forman.cursojava.cajero.IFCuenta#ingresa(float)
	 */
    public void ingresa(float cantidad) {
    	this.saldo += cantidad;
    }
    
    /* (non-Javadoc)
	 * @see es.forman.cursojava.cajero.IFCuenta#setNumero(java.lang.String)
	 */
    public void setNumero(String s) {
    	this.numero = s;
    }
    
    /* (non-Javadoc)
	 * @see es.forman.cursojava.cajero.IFCuenta#getNumero()
	 */
    public String getNumero() {
    	return this.numero;
    }
    
    /* (non-Javadoc)
	 * @see es.forman.cursojava.cajero.IFCuenta#toString()
	 */
    public String toString() {
    	return "CCC #"+this.numero;
    }
    

}
