//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cajero.java
//  @ Date : 16/03/2006
//  @ Author : Jose Carlos Roman Rubio
//
//

package es.forman.cursojava.cajero;

public class Cajero {
    static int numCuentas=0;

	public boolean identificaCliente(CuentaCorriente cuenta, int pin) {
        return cuenta.getPin()==pin;
	
	}
       
}