//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuenta.java
//  @ Date : 16/03/2006
//  @ Author : José Carlos Román Rubio
//
//



package es.forman.cursojava.cajero;


public abstract class Cuenta {
     
        private Cliente cliente;
        public Cuenta(Cliente cliente) {
           this.cliente=cliente;
        }
      
	abstract public void ingresaDinero(float cantidad, Cuenta cuentaAux);
	
	abstract public boolean retiraDinero(float cantidad, Cuenta ahorro, Cuenta credito);
	
	abstract public float consultaSaldo();
        
	abstract public boolean transferencia(Cuenta c, float cantidad); 

}