//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Circulo.java
//  @ Date : 13/03/2006
//  @ Author : 
//
//

package es.forman.cursojava.formas;


public class Circulo extends FormaGeometrica {
	private float r;

	final float PI= 3.1416f;
        
	
        public Circulo(float r) {
           this.r=r;
        }
   
        public float getRadio() {
           return r;
        }
        public float getSuperficie() {
         return PI*this.r*this.r;
        }
        
        public float getLongitud(){
            return 2*PI*this.r;
        
        }
        public Cuadrado devuelveMinimoCuadrado() {
           Cuadrado cuadrado= new Cuadrado(2*this.r);
           return cuadrado;
        }
}