//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Coordenadas.java
//  @ Date : 13/03/2006
//  @ Author : 
//
//



package es.forman.cursojava.formas;


public class Coordenadas {
	private int x;
	private int y;
	public FormaGeometrica se_coloca;
	
	
	public void setX(int x) {
	
	}
	
	public void setY(int y) {
	
	}
	
	public int getX() {
	  return this.x;
	}
	
	public int getY() {
	  return y;
	}
}