//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Foto.java
//  @ Date : 13/03/2006
//  @ Author : 
//
//



package es.forman.cursojava.formas;


public class Foto {
	public String nombreArchivo;
	public void cargarFoto(String nombre) {
	
	}
	
	public Foto() {
	
	}
}
