//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 16/03/2006
//  @ Author : Jose Carlos Roman Rubio
//
//

package es.forman.cursojava.cajero;


public class Cliente {
	private String nombre;
	private String dni;
	private String direccion;
	
        public Cliente(String dni) {
                this.dni=dni;
        }
     // getters, setters, etc
}