//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CuentaCredito.java
//  @ Date : 16/03/2006
//  @ Author : Jose Carlos Roman Rubio
//
//

package es.forman.cursojava.cajero;


public class CuentaCredito extends Cuenta {
        
        private float saldoCuentaCredito; 
        static final float SALDOINICIAL = 3000f;
        static final float EURIBOR = 0.03f;
	static final float comision=0.01f;;
        private float fondoComision;
        
        public CuentaCredito(Cliente cliente, Cuenta cc, Cuenta ca) {
            super(cliente);
            this.saldoCuentaCredito=SALDOINICIAL;
            cc.retiraDinero(comision*this.saldoCuentaCredito,ca,this);
        }
              
        public float consultaSaldo () {
          return this.saldoCuentaCredito;
        }
      
      
        public boolean transferencia(Cuenta cA, float cantidad) {
   
                if (cantidad < this.saldoCuentaCredito-fondoComision) {   
                   cA.ingresaDinero(cantidad,cA);
                   return retiraDinero(cantidad,cA,this);
                }
                else return false;
	}

      
        public boolean retiraDinero(float cantidad, Cuenta ahorro, Cuenta credito) {
               if (cantidad < this.saldoCuentaCredito-fondoComision) {  
                   fondoComision+=(EURIBOR*cantidad); 
                   this.saldoCuentaCredito-= (cantidad+fondoComision);
                   return true;
              }
              else
                  return false;
        }
        
        public void ingresaDinero(float cantidad, Cuenta cuentaAux) {
               this.saldoCuentaCredito+= cantidad;
        }
}