//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CuentaAhorro.java
//  @ Date : 16/03/2006
//  @ Author : José Carlos
//
//

package es.forman.cursojava.cajero;

public class CuentaAhorro extends Cuenta {
      
        private float saldoCuentaAhorro;
        
     
        public CuentaAhorro(Cliente cliente) {
           super(cliente);
        }
        public float consultaSaldo () {
          return this.saldoCuentaAhorro;
        }
     
        public void ingresaDinero(float cantidad, Cuenta cuentaAux) {
           this.saldoCuentaAhorro+=cantidad; 
        }
        
        public boolean retiraDinero(float cantidad, Cuenta cc, Cuenta credito) {
          if (this.saldoCuentaAhorro>cantidad) {
                this.saldoCuentaAhorro-=cantidad;
                return true;  
          } 
          else return false;
        }
        
        public boolean transferencia(Cuenta cc, float cantidad) {
           if (cantidad+cc.consultaSaldo()<CuentaCorriente.SALDOMAXIMO) {
                  cc.ingresaDinero(cantidad,this);
                  return this.retiraDinero(cantidad,cc,null);
           }
           else return false;
        }
         
}